version: '3.3'
services:
    mssql:
        hostname: mssql
        restart: unless-stopped
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=${GLOBAL_PASSWORD}
        ports:
            - '1433:1433'
        container_name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        networks:
            - mssql-net
networks:
    mssql-net:
        external: true