version: "3"
services:
  redis:
    restart: unless-stopped
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/redis/config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
