version: "3"
services:
  redis:
    container_name: redis-server
    restart: unless-stopped
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - coco-net
    volumes:
      - ../data/redis/config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

networks:
    coco-net:
        external: true