version: "3"
services:
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    ports:
      - "9000:9000"
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    networks:
      coco-net:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: "http://elastic:9200"
    depends_on:
      - elastic
    ports:
      - "5601:5601"
    networks:
      coco-net:

networks:
  coco-net:
