version: "3"
services:
  elastic:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      # - "ELASTIC_USERNAME=${ELASTIC_USERNAME}"
      # - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      # - "xpack.security.enabled=true"
    networks:
      dev-net:

networks:
  dev-net:
