version: "3"
services:
  redis:
    container_name: redis-server
    restart: unless-stopped
    image: redis:latest
    ports:
      - 10100:6379
    volumes:
      - ./data/redis/config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]