version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres
        restart: unless-stopped
        networks:
            - coco-net
        ports: 
            - "5432:5432"
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - '../data/postgresql:/var/lib/postgresql/data'
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        networks:
            - coco-net
        environment:
            PGADMIN_DEFAULT_EMAIL: root@example.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"
        depends_on:
            - postgres

networks:
    coco-net:
        external: true